"""Content definitions for service landing pages."""

SERVICE_PAGES = {
    'personal_banking': {
        'title': 'Personal Banking',
        'meta_description': 'Checking, savings, and money market accounts with competitive rates, no hidden fees, and 24/7 digital banking from NovaPlusBank.',
        'eyebrow': 'Personal Banking',
        'headline': 'Everyday Banking,<br>Built Around You.',
        'intro': "From free checking to high-yield savings, NovaPlusBank gives you the tools to manage, grow, and protect your money — with rates and service you won't find at big banks.",
        'hero_badges': [
            {'icon': 'fa-piggy-bank', 'text': '3.75% APY Savings'},
            {'icon': 'fa-mobile-screen', 'text': 'Free Mobile Banking'},
            {'icon': 'fa-shield-halved', 'text': 'FDIC Insured'},
        ],
        'stats': [
            {'value': '3.75%', 'label': 'High Yield APY'},
            {'value': '$0', 'label': 'Checking Fees'},
            {'value': '55K+', 'label': 'Free ATMs'},
            {'value': '24/7', 'label': 'Digital Access'},
        ],
        'products_heading': 'Accounts & Products',
        'products_subheading': 'Simple, transparent accounts designed to help your money work harder.',
        'products': [
            {
                'icon': 'fa-wallet',
                'icon_bg': 'blue',
                'name': 'Free Checking',
                'rate': '$0',
                'rate_label': 'Monthly Fee',
                'description': 'No minimum balance, free debit card, and unlimited online transfers.',
                'badge': 'Popular',
            },
            {
                'icon': 'fa-piggy-bank',
                'icon_bg': 'gray',
                'name': 'High Yield Savings',
                'rate': '3.75%',
                'rate_label': 'APY*',
                'description': 'Earn more on every dollar with our member-exclusive savings rate.',
                'badge': 'Featured',
            },
            {
                'icon': 'fa-certificate',
                'icon_bg': 'gray',
                'name': 'Certificates',
                'rate': '3.65%',
                'rate_label': 'APY*',
                'description': 'Lock in competitive rates with terms from 6 to 60 months.',
                'badge': None,
            },
            {
                'icon': 'fa-chart-line',
                'icon_bg': 'gray',
                'name': 'Money Market',
                'rate': '3.50%',
                'rate_label': 'APY*',
                'description': 'Higher yields with check-writing privileges and tiered rates.',
                'badge': None,
            },
        ],
        'features_heading': 'Banking That Fits Your Life',
        'features_subheading': 'Everything you need to manage your finances — online, on mobile, or in branch.',
        'features': [
            {
                'icon': 'fa-mobile-screen-button',
                'title': 'Mobile & Online Banking',
                'description': 'Check balances, deposit checks, pay bills, and transfer funds anytime from any device.',
            },
            {
                'icon': 'fa-money-bill-transfer',
                'title': 'Free Transfers & Bill Pay',
                'description': 'Send money to friends and pay bills at no extra cost with our digital tools.',
            },
            {
                'icon': 'fa-globe',
                'title': 'Nationwide ATM Access',
                'description': '55,000+ surcharge-free ATMs across the country, plus fee rebates on out-of-network use.',
            },
            {
                'icon': 'fa-bell',
                'title': 'Account Alerts',
                'description': 'Custom notifications for low balances, large transactions, and deposit confirmations.',
            },
        ],
        'benefits_heading': 'Why Members Choose Us',
        'benefits_subheading': 'Member-owned banking means better rates, lower fees, and service that actually cares.',
        'benefits': [
            {
                'icon': 'fa-hand-holding-dollar',
                'title': 'Better Rates',
                'description': 'As a credit union, we return profits to members through higher savings yields and lower loan rates.',
            },
            {
                'icon': 'fa-user-shield',
                'title': 'No Hidden Fees',
                'description': 'Transparent pricing with no monthly maintenance fees on checking and no surprise charges.',
            },
            {
                'icon': 'fa-headset',
                'title': 'Real Support',
                'description': 'Talk to a person — not a phone tree. Our team is available 24/7 by phone and chat.',
            },
        ],
        'cta_heading': 'Open Your Personal Account',
        'cta_text': 'Join 50,000+ members banking smarter. Open online in minutes — no minimum balance required.',
    },
    'business_banking': {
        'title': 'Business Banking',
        'meta_description': 'Business checking, savings, merchant services, and credit lines to help your company grow with NovaPlusBank.',
        'eyebrow': 'Business Banking',
        'headline': 'Banking Built for<br>Business Growth.',
        'intro': "Whether you're a startup, a growing company, or an established enterprise, NovaPlusBank offers the accounts, tools, and dedicated support your business needs to thrive.",
        'hero_badges': [
            {'icon': 'fa-briefcase', 'text': 'Dedicated Advisors'},
            {'icon': 'fa-credit-card', 'text': 'Merchant Services'},
            {'icon': 'fa-chart-pie', 'text': 'Cash Management'},
        ],
        'stats': [
            {'value': '$0', 'label': 'Business Checking Fees'},
            {'value': '2.5%', 'label': 'Merchant Rate'},
            {'value': 'Same-Day', 'label': 'ACH Transfers'},
            {'value': 'Dedicated', 'label': 'Relationship Manager'},
        ],
        'products_heading': 'Business Solutions',
        'products_subheading': 'Full-service business banking from day one to scale-up and beyond.',
        'products': [
            {
                'icon': 'fa-building',
                'icon_bg': 'blue',
                'name': 'Business Checking',
                'rate': '$0',
                'rate_label': 'Monthly Fee',
                'description': 'Unlimited transactions, online bill pay, and mobile deposit for your team.',
                'badge': 'Popular',
            },
            {
                'icon': 'fa-vault',
                'icon_bg': 'gray',
                'name': 'Business Savings',
                'rate': '3.25%',
                'rate_label': 'APY*',
                'description': 'Park your operating reserves and earn competitive returns.',
                'badge': None,
            },
            {
                'icon': 'fa-store',
                'icon_bg': 'gray',
                'name': 'Merchant Services',
                'rate': '2.5%',
                'rate_label': 'Starting Rate',
                'description': 'Accept credit and debit payments in-store, online, or on the go.',
                'badge': None,
            },
            {
                'icon': 'fa-file-invoice-dollar',
                'icon_bg': 'gray',
                'name': 'Business Credit Line',
                'rate': '9.99%',
                'rate_label': 'APR*',
                'description': 'Flexible revolving credit for inventory, payroll, or seasonal cash flow needs.',
                'badge': None,
            },
        ],
        'features_heading': 'Tools to Run Your Business',
        'features_subheading': 'Powerful cash management and digital tools that save you time and money.',
        'features': [
            {
                'icon': 'fa-users-gear',
                'title': 'Multi-User Access',
                'description': 'Assign roles and permissions so your team can manage accounts securely.',
            },
            {
                'icon': 'fa-money-check-dollar',
                'title': 'Payroll & ACH',
                'description': 'Run payroll and schedule vendor payments with same-day and next-day options.',
            },
            {
                'icon': 'fa-file-export',
                'title': 'QuickBooks Integration',
                'description': 'Sync transactions automatically with QuickBooks, Xero, and other accounting platforms.',
            },
            {
                'icon': 'fa-handshake',
                'title': 'Dedicated Advisor',
                'description': 'A named relationship manager who understands your industry and growth goals.',
            },
        ],
        'benefits_heading': 'Partner With a Bank That Gets It',
        'benefits_subheading': 'Local decision-making, competitive rates, and lending that looks at the full picture.',
        'benefits': [
            {
                'icon': 'fa-seedling',
                'title': 'Startup Friendly',
                'description': 'Accounts and credit for new businesses — we look at your plan, not just your history.',
            },
            {
                'icon': 'fa-truck-fast',
                'title': 'Fast Decisions',
                'description': 'Local underwriting means faster loan approvals than national banks.',
            },
            {
                'icon': 'fa-hand-holding-dollar',
                'title': 'Growth Capital',
                'description': 'Term loans, lines of credit, and SBA lending to fuel your next chapter.',
            },
        ],
        'cta_heading': 'Open a Business Account',
        'cta_text': 'Schedule a free consultation with a business banking advisor or apply online today.',
    },
    'loans_credit': {
        'title': 'Loans & Credit',
        'meta_description': 'Personal loans, auto loans, mortgages, and home equity lines with competitive rates and flexible terms from NovaPlusBank.',
        'eyebrow': 'Loans & Credit',
        'headline': 'Lending That Works<br>for Your Goals.',
        'intro': 'From buying your first car to refinancing your home, NovaPlusBank offers competitive rates, transparent terms, and a lending team that guides you every step of the way.',
        'hero_badges': [
            {'icon': 'fa-house', 'text': 'Mortgages'},
            {'icon': 'fa-car', 'text': 'Auto Loans'},
            {'icon': 'fa-hand-holding-dollar', 'text': 'Personal Loans'},
        ],
        'stats': [
            {'value': '15.49%', 'label': 'Personal Loan APR*'},
            {'value': '5.99%', 'label': 'Auto Loan APR*'},
            {'value': '6.25%', 'label': '30-Yr Mortgage*'},
            {'value': '48hr', 'label': 'Pre-Approval'},
        ],
        'products_heading': 'Loan Products',
        'products_subheading': 'Flexible financing options with rates that beat most national lenders.',
        'products': [
            {
                'icon': 'fa-house',
                'icon_bg': 'blue',
                'name': 'Home Mortgages',
                'rate': '6.25%',
                'rate_label': '30-Yr Fixed*',
                'description': 'Fixed and adjustable rates, FHA, VA, and conventional options available.',
                'badge': 'Popular',
            },
            {
                'icon': 'fa-car',
                'icon_bg': 'gray',
                'name': 'Auto Loans',
                'rate': '5.99%',
                'rate_label': 'APR*',
                'description': 'New and used vehicle financing with terms up to 72 months.',
                'badge': None,
            },
            {
                'icon': 'fa-hand-holding-dollar',
                'icon_bg': 'gray',
                'name': 'Personal Loans',
                'rate': '15.49%',
                'rate_label': 'APR*',
                'description': 'Unsecured loans for debt consolidation, home improvement, or major purchases.',
                'badge': None,
            },
            {
                'icon': 'fa-key',
                'icon_bg': 'gray',
                'name': 'Home Equity',
                'rate': '7.50%',
                'rate_label': 'HELOC*',
                'description': 'Tap your home equity for renovations, education, or emergency expenses.',
                'badge': None,
            },
        ],
        'features_heading': 'A Smoother Borrowing Experience',
        'features_subheading': 'Local underwriting, clear communication, and support from application to closing.',
        'features': [
            {
                'icon': 'fa-clock',
                'title': 'Fast Pre-Approval',
                'description': "Get pre-approved in as little as 48 hours with a soft credit check that won't hurt your score.",
            },
            {
                'icon': 'fa-calculator',
                'title': 'Transparent Terms',
                'description': "No prepayment penalties on most loans. Know exactly what you'll pay before you sign.",
            },
            {
                'icon': 'fa-user-tie',
                'title': 'Dedicated Loan Officer',
                'description': 'One point of contact from application through closing — no hand-offs or hold music.',
            },
            {
                'icon': 'fa-rotate',
                'title': 'Refinancing Options',
                'description': 'Lower your rate or monthly payment by refinancing existing auto, home, or personal loans.',
            },
        ],
        'benefits_heading': 'Member Rates, Member Service',
        'benefits_subheading': 'Credit union lending means lower rates and decisions made by people who know your community.',
        'benefits': [
            {
                'icon': 'fa-percent',
                'title': 'Competitive Rates',
                'description': 'Rates consistently below national bank averages on mortgages, auto, and personal loans.',
            },
            {
                'icon': 'fa-house-circle-check',
                'title': 'First-Time Buyer Programs',
                'description': 'Down payment assistance and reduced closing costs for qualifying first-time homebuyers.',
            },
            {
                'icon': 'fa-file-signature',
                'title': 'Flexible Terms',
                'description': 'Choose repayment terms that fit your budget — from 12 months to 30 years.',
            },
        ],
        'cta_heading': 'Get Pre-Approved Today',
        'cta_text': 'Apply online in minutes or speak with a lending specialist about the right loan for your goals.',
    },
    'cards': {
        'title': 'Credit Cards',
        'meta_description': 'NovaPlusBank credit cards with cash back rewards, low rates, and no annual fees. Find the card that fits your lifestyle.',
        'eyebrow': 'Credit Cards',
        'headline': 'Cards With Real<br>Rewards & Value.',
        'intro': 'Whether you want cash back on everyday spending, a low rate for balance transfers, or a card to build credit — NovaPlusBank has a card designed for how you actually live.',
        'hero_badges': [
            {'icon': 'fa-percent', 'text': '4.00% Intro APR'},
            {'icon': 'fa-gift', 'text': 'Cash Back Rewards'},
            {'icon': 'fa-ban', 'text': 'No Annual Fee'},
        ],
        'stats': [
            {'value': '4.00%', 'label': 'Intro APR*'},
            {'value': '1.5%', 'label': 'Cash Back'},
            {'value': '$0', 'label': 'Annual Fee'},
            {'value': '$0', 'label': 'Foreign Transaction Fee'},
        ],
        'products_heading': 'Our Card Lineup',
        'products_subheading': 'Four cards built for different needs — all with member-friendly terms.',
        'products': [
            {
                'icon': 'fa-money-bill-wave',
                'icon_bg': 'blue',
                'name': 'Cash Back Rewards',
                'rate': '1.5%',
                'rate_label': 'Cash Back',
                'description': 'Earn unlimited 1.5% cash back on every purchase with no category restrictions.',
                'badge': 'Popular',
            },
            {
                'icon': 'fa-arrow-down-wide-short',
                'icon_bg': 'gray',
                'name': 'Low Rate Card',
                'rate': '4.00%',
                'rate_label': 'Intro APR*',
                'description': 'Ideal for balance transfers with a low introductory rate and no transfer fee.',
                'badge': 'Featured',
            },
            {
                'icon': 'fa-lock',
                'icon_bg': 'gray',
                'name': 'Secured Card',
                'rate': 'Build',
                'rate_label': 'Credit',
                'description': 'Start or rebuild credit with a secured card that graduates to unsecured.',
                'badge': None,
            },
            {
                'icon': 'fa-briefcase',
                'icon_bg': 'gray',
                'name': 'Business Rewards',
                'rate': '2.0%',
                'rate_label': 'Cash Back',
                'description': 'Earn 2% on business purchases with employee cards and expense tracking tools.',
                'badge': None,
            },
        ],
        'features_heading': 'Card Benefits Included',
        'features_subheading': 'Every NovaPlusBank card comes with protections and perks at no extra cost.',
        'features': [
            {
                'icon': 'fa-shield-halved',
                'title': 'Fraud Protection',
                'description': 'Zero liability on unauthorized charges with 24/7 monitoring and instant card lock via mobile app.',
            },
            {
                'icon': 'fa-mobile-screen',
                'title': 'Digital Wallet Ready',
                'description': 'Add to Apple Pay, Google Pay, or Samsung Pay for secure contactless payments.',
            },
            {
                'icon': 'fa-globe',
                'title': 'No Foreign Fees',
                'description': 'Use your card abroad without foreign transaction fees on any of our card products.',
            },
            {
                'icon': 'fa-chart-simple',
                'title': 'Spending Insights',
                'description': 'Track spending by category and set budgets directly in online and mobile banking.',
            },
        ],
        'benefits_heading': 'More Than Just a Card',
        'benefits_subheading': "Member-owned means we don't nickel-and-dime you with fees other banks charge.",
        'benefits': [
            {
                'icon': 'fa-gift',
                'title': 'Real Rewards',
                'description': 'Cash back you can actually use — deposited directly to your NovaPlusBank account monthly.',
            },
            {
                'icon': 'fa-credit-card',
                'title': 'No Annual Fees',
                'description': 'Every card in our lineup is free to carry. No surprise renewal charges.',
            },
            {
                'icon': 'fa-arrow-up-right-dots',
                'title': 'Credit Building',
                'description': 'Responsible use reported to all three bureaus to help build your credit history.',
            },
        ],
        'cta_heading': 'Find Your Perfect Card',
        'cta_text': 'Apply online and get a decision in minutes. Already a member? Add a card through online banking.',
    },
    'grants_aid': {
        'title': 'Grants & Aid',
        'meta_description': 'Financial assistance programs from NovaPlusBank including first-time homebuyer aid, small business grants, and emergency member support.',
        'eyebrow': 'Grants & Aid',
        'headline': 'Support When<br>You Need It Most.',
        'intro': 'NovaPlusBank reinvests in our members and communities through grants, down payment assistance, and emergency aid programs — because banking should lift people up, not hold them back.',
        'hero_badges': [
            {'icon': 'fa-house', 'text': 'Homebuyer Aid'},
            {'icon': 'fa-seedling', 'text': 'Business Grants'},
            {'icon': 'fa-heart', 'text': 'Emergency Support'},
        ],
        'stats': [
            {'value': '$500K+', 'label': 'Annual Grants'},
            {'value': '$10K', 'label': 'Max Homebuyer Aid'},
            {'value': '5,000+', 'label': 'People Served/Year'},
            {'value': '12', 'label': 'Community Programs'},
        ],
        'products_heading': 'Assistance Programs',
        'products_subheading': 'Financial support for members and communities who qualify.',
        'products': [
            {
                'icon': 'fa-house-chimney',
                'icon_bg': 'blue',
                'name': 'First-Time Homebuyer',
                'rate': 'Up to $10K',
                'rate_label': 'Assistance',
                'description': 'Down payment and closing cost assistance for qualifying first-time buyers.',
                'badge': 'Popular',
            },
            {
                'icon': 'fa-seedling',
                'icon_bg': 'gray',
                'name': 'Small Business Grant',
                'rate': 'Up to $5K',
                'rate_label': 'Grant',
                'description': 'Seed funding for minority-owned and women-owned local businesses.',
                'badge': 'Featured',
            },
            {
                'icon': 'fa-graduation-cap',
                'icon_bg': 'gray',
                'name': 'Education Scholarship',
                'rate': '$2,500',
                'rate_label': 'Per Award',
                'description': 'Annual scholarships for members and dependents pursuing higher education.',
                'badge': None,
            },
            {
                'icon': 'fa-hand-holding-heart',
                'icon_bg': 'gray',
                'name': 'Emergency Member Aid',
                'rate': 'Up to $2K',
                'rate_label': 'Assistance',
                'description': 'Short-term relief for members facing unexpected financial hardship.',
                'badge': None,
            },
        ],
        'features_heading': 'How to Apply',
        'features_subheading': 'Simple application processes with local review and fast decisions.',
        'features': [
            {
                'icon': 'fa-file-lines',
                'title': 'Easy Application',
                'description': 'Apply online or at any branch. Most programs require basic documentation and a brief interview.',
            },
            {
                'icon': 'fa-clock',
                'title': 'Quick Decisions',
                'description': 'Local review committees meet monthly — most applicants hear back within 30 days.',
            },
            {
                'icon': 'fa-user-check',
                'title': 'Member-Focused Review',
                'description': 'Applications reviewed by community members who understand local needs and challenges.',
            },
            {
                'icon': 'fa-handshake-angle',
                'title': 'Ongoing Support',
                'description': 'Grant recipients get paired with a financial counselor for guidance beyond the award.',
            },
        ],
        'benefits_heading': 'Community Commitment',
        'benefits_subheading': "As a not-for-profit credit union, giving back isn't optional — it's who we are.",
        'benefits': [
            {
                'icon': 'fa-chalkboard-user',
                'title': 'Financial Literacy',
                'description': 'Free workshops on budgeting, credit, and homeownership for members and the public.',
            },
            {
                'icon': 'fa-people-group',
                'title': 'Community Partnerships',
                'description': 'We partner with local nonprofits, schools, and housing agencies to maximize impact.',
            },
            {
                'icon': 'fa-piggy-bank',
                'title': 'Reinvested Profits',
                'description': 'Earnings go back to members through grants, better rates, and lower fees — not Wall Street.',
            },
        ],
        'cta_heading': 'See If You Qualify',
        'cta_text': 'Contact our community programs team to learn about eligibility and upcoming application deadlines.',
    },
}

SERVICE_URL_NAMES = frozenset(SERVICE_PAGES.keys())
