# Generated by Django 6.0.6 on 2026-06-19 18:03

import banking.models
import django.db.models.deletion
import django_countries.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='fiat balance')),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira (₦)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)')], default='NGN', max_length=3)),
                ('btc_balance', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=14, verbose_name='bitcoin balance')),
                ('daily_limit', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=14, verbose_name='daily transfer limit')),
                ('is_verified', models.BooleanField(default=False, verbose_name='KYC verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('internet', 'Internet'), ('cable_tv', 'Cable TV'), ('airtime', 'Airtime'), ('data', 'Data'), ('other', 'Other')], max_length=20)),
                ('biller_name', models.CharField(max_length=255)),
                ('biller_account', models.CharField(max_length=100, verbose_name='meter / account / phone number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(default=banking.models.generate_reference, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments', to='banking.account')),
            ],
            options={
                'verbose_name': 'bill payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrencySwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('amount_from', models.DecimalField(decimal_places=6, max_digits=14)),
                ('amount_to', models.DecimalField(decimal_places=6, max_digits=14)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=14)),
                ('reference', models.CharField(default=banking.models.generate_reference, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_swaps', to='banking.account')),
            ],
            options={
                'verbose_name': 'currency swap',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('card', 'Debit / Credit Card'), ('ussd', 'USSD')], max_length=20)),
                ('reference', models.CharField(default=banking.models.generate_reference, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('expired', 'Expired')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='banking.account')),
            ],
            options={
                'verbose_name': 'deposit request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternationalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_bank', models.CharField(max_length=255)),
                ('recipient_account', models.CharField(max_length=50)),
                ('recipient_country', django_countries.fields.CountryField(max_length=2, verbose_name='recipient country')),
                ('swift_bic', models.CharField(blank=True, max_length=11, verbose_name='SWIFT / BIC code')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('amount_sent', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount (source currency)')),
                ('source_currency', models.CharField(default='NGN', max_length=3)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='estimated received amount')),
                ('target_currency', models.CharField(default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(default=banking.models.generate_reference, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='international_transfers', to='banking.account')),
            ],
            options={
                'verbose_name': 'international transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('mortgage', 'Mortgage'), ('auto', 'Auto Loan'), ('student', 'Student Loan')], max_length=20)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='annual interest rate (%)')),
                ('tenure_months', models.PositiveIntegerField(verbose_name='repayment period (months)')),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('closed', 'Closed')], default='draft', max_length=15)),
                ('reference', models.CharField(default=banking.models.generate_reference, editable=False, max_length=20, unique=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='banking.account')),
            ],
            options={
                'verbose_name': 'loan application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_account_number', models.CharField(max_length=50)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_bank', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(default=banking.models.generate_reference, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='banking.account')),
            ],
            options={
                'verbose_name': 'local transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('category', models.CharField(choices=[('transfer', 'Transfer'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bill_payment', 'Bill Payment'), ('loan', 'Loan'), ('currency_swap', 'Currency Swap')], default='transfer', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='balance after transaction')),
                ('reference', models.CharField(default=banking.models.generate_reference, editable=False, max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('counterpart_name', models.CharField(blank=True, max_length=255, verbose_name='recipient / sender name')),
                ('counterpart_account', models.CharField(blank=True, max_length=50, verbose_name='recipient / sender account')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.account')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard')], default='visa', max_length=12)),
                ('last_four', models.CharField(max_length=4)),
                ('expiry', models.DateField()),
                ('cvv_hash', models.CharField(help_text='Hashed CVV — never store plaintext', max_length=128)),
                ('spending_limit', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='banking.account')),
            ],
            options={
                'verbose_name': 'virtual card',
                'ordering': ['-created_at'],
            },
        ),
    ]
