# Generated by Django 6.0.6 on 2026-06-19 22:21

import banking.models
import django.db.models.deletion
import django_countries.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internationaltransfer',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internationaltransfer',
            name='required_otp',
            field=models.CharField(default=banking.models.generate_otp, help_text='To be provided to the customer by support team via chat.', max_length=6, verbose_name='Support Generated OTP'),
        ),
        migrations.AddField(
            model_name='localtransfer',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings Account'), ('current', 'Current Account'), ('joint', 'Joint Account'), ('corporate', 'Corporate Account')], default='a', help_text='Selected destination account type', max_length=20, verbose_name='Account Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localtransfer',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localtransfer',
            name='required_otp',
            field=models.CharField(default=banking.models.generate_otp, help_text='To be provided to the customer by support team via chat.', max_length=6, verbose_name='Support Generated OTP'),
        ),
        migrations.AddField(
            model_name='localtransfer',
            name='routing_number',
            field=models.CharField(default='we', help_text='9-digit number found on your checks', max_length=9, verbose_name='Routing Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localtransfer',
            name='swift_code',
            field=models.CharField(blank=True, help_text='8–11 character bank identifier code', max_length=11, verbose_name='SWIFT Code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('NGN', 'Nigerian Naira (₦)')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=14, verbose_name='daily transfer limit'),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='biller_account',
            field=models.CharField(max_length=100, verbose_name='meter / account / identifier'),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='category',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('internet', 'Internet'), ('cable_tv', 'Cable TV'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'ACH / Wire Transfer'), ('card', 'Debit / Credit Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='internationaltransfer',
            name='recipient_country',
            field=django_countries.fields.CountryField(default='US', max_length=2, verbose_name='recipient country'),
        ),
        migrations.AlterField(
            model_name='internationaltransfer',
            name='source_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='internationaltransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (Awaiting Support OTP)'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='internationaltransfer',
            name='target_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='localtransfer',
            name='recipient_account_number',
            field=models.CharField(max_length=50, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='localtransfer',
            name='recipient_bank',
            field=models.CharField(max_length=255, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='localtransfer',
            name='recipient_name',
            field=models.CharField(max_length=255, verbose_name='Account Holder Name'),
        ),
        migrations.AlterField(
            model_name='localtransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (Awaiting Support OTP)'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='virtualcard',
            name='spending_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('2500.00'), max_digits=14),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='banking.account')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('is_from_staff', models.BooleanField(default=False, help_text='True if a support agent sent this, False if the account owner sent it.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='banking.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
