# Generated by Django 6.0.6 on 2026-06-20 13:22

import banking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_internationaltransfer_is_otp_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='linked_action',
            field=models.CharField(blank=True, help_text='e.g., Pay Bills, Outbound Wire, Loan Authorization Exception', max_length=100),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='meta_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Preserved raw transaction data submitted by the client user form.'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='support_id',
            field=models.CharField(default=banking.models.generate_support_id, help_text='Unique support reference ID code used for resolving operations.', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, help_text='Custom title configured by administrators, or automatically generated from actions.', max_length=255),
        ),
    ]
