# Generated by Django 6.0.6 on 2026-06-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_chatsession_options_chatsession_linked_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Administrative Review'), ('APPROVED', 'Approved & Actioned'), ('DECLINED', 'Declined / Rejected'), ('RESOLVED', 'Resolved & Closed')], default='PENDING', help_text='Current state of the request. Admin handles manual execution updates here.', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='General structural archive toggle flag.'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='linked_action',
            field=models.CharField(blank=True, help_text='The feature context being routed (e.g., Local Transfer, Pay Bills, Virtual Card Request)', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='meta_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Preserved raw submission data captured from the client form structure.'),
        ),
    ]
