# Generated by Django 6.0.6 on 2026-06-20 16:47

import banking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_chatsession_status_alter_chatsession_is_resolved_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Model of the underlying transaction (e.g. LocalTransfer, InternationalTransfer).', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationaltransfer',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internationaltransfer',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, help_text='otp_sent_at + 48h. The code stops being redeemable after this point.', null=True),
        ),
        migrations.AddField(
            model_name='internationaltransfer',
            name='otp_sent_at',
            field=models.DateTimeField(blank=True, help_text='Stamped when the agent marks the code as shared with the customer in chat. This — not the creation time — starts the 48h window.', null=True),
        ),
        migrations.AddField(
            model_name='localtransfer',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='localtransfer',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, help_text='otp_sent_at + 48h. The code stops being redeemable after this point.', null=True),
        ),
        migrations.AddField(
            model_name='localtransfer',
            name='otp_sent_at',
            field=models.DateTimeField(blank=True, help_text='Stamped when the agent marks the code as shared with the customer in chat. This — not the creation time — starts the 48h window.', null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='linked_action',
            field=models.CharField(blank=True, help_text="Human-readable label for the process (e.g., 'Local Transfer', 'International Transfer').", max_length=100),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='meta_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Non-sensitive contextual notes captured for the agent. Never store credentials here.'),
        ),
        migrations.AlterField(
            model_name='internationaltransfer',
            name='required_otp',
            field=models.CharField(default=banking.models.generate_otp, editable=False, help_text="Generated automatically when this transfer is created. Visible to support staff only — once research is done, the agent copies this code and pastes it into the customer's verification chat.", max_length=6, verbose_name='Support OTP'),
        ),
        migrations.AlterField(
            model_name='internationaltransfer',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending — Awaiting Support Review'), ('otp_issued', 'OTP Sent — Awaiting Customer Confirmation'), ('completed', 'Completed'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='localtransfer',
            name='required_otp',
            field=models.CharField(default=banking.models.generate_otp, editable=False, help_text="Generated automatically when this transfer is created. Visible to support staff only — once research is done, the agent copies this code and pastes it into the customer's verification chat.", max_length=6, verbose_name='Support OTP'),
        ),
        migrations.AlterField(
            model_name='localtransfer',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending — Awaiting Support Review'), ('otp_issued', 'OTP Sent — Awaiting Customer Confirmation'), ('completed', 'Completed'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending_review', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.UniqueConstraint(condition=models.Q(('content_type__isnull', False)), fields=('content_type', 'object_id'), name='one_verification_session_per_object'),
        ),
    ]
