# Generated by Django 6.0.6 on 2026-06-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_chatsession_content_type_chatsession_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationaltransfer',
            name='amount_received',
        ),
        migrations.RemoveField(
            model_name='internationaltransfer',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='internationaltransfer',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='internationaltransfer',
            name='recipient_bank',
        ),
        migrations.RemoveField(
            model_name='internationaltransfer',
            name='recipient_country',
        ),
        migrations.RemoveField(
            model_name='internationaltransfer',
            name='swift_bic',
        ),
        migrations.RemoveField(
            model_name='internationaltransfer',
            name='target_currency',
        ),
        migrations.AddField(
            model_name='internationaltransfer',
            name='payment_method',
            field=models.CharField(choices=[('wire', 'Wire Transfer'), ('crypto', 'Cryptocurrency'), ('paypal', 'PayPal'), ('wise', 'Wise Transfer'), ('cashapp', 'Cash App'), ('skrill', 'Skrill'), ('venmo', 'Venmo'), ('zelle', 'Zelle'), ('revolut', 'Revolut'), ('alipay', 'Alipay'), ('wechat', 'WeChat Pay')], default='wire', max_length=20),
        ),
        migrations.AddField(
            model_name='internationaltransfer',
            name='routing_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internationaltransfer',
            name='settlement_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='internationaltransfer',
            name='recipient_account',
            field=models.CharField(max_length=255),
        ),
    ]
